### ISSUE TITLE
npm start generate error like below

### ISSUE THREAD

**Issue by speedy32** [DenisVuyka/ng2-dynamic-content#3]
> ng2samples-blank@0.2.0 start C:\Users\rurbanski1\Projekty\ng2-dynamic-content
> tsc && concurrently "tsc -w" "npm run serve"

node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ng2samples-blank@0.2.0 start: `tsc && concurrently "tsc -w" "npm run serve" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ng2samples-blank@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rurbanski1\AppData\Roaming\npm-cache\_logs\2017-07-21T12_03_26_512Z-debug.log

node v6.10.3
npm v5.3.0

**Comment by speedy32** [comment]
Use yarn instead to install packages. Then npm start

**Comment by DenisVuyka** [comment]
Thanks for pointing out. Updated code to Angular 4.3.1 and added new lock files for Yarn and NPM 5
